### ISSUE TITLE
String methods inconsistent

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#107]
There are several variants of String method indexOf supported by Grace, but they are not consistent.  In the variants.  Grace supports:
indexOf(sub: String) -> Number
indexOf(sub:String) ifAbsent(absent:Block0<W>) −> Number | W
indexOf(pattern:String)startingAt(offset)ifAbsent (action:Block0<W>) −> Number | W 

We are missing the method:
indexOf (pattern:String) startingAt (offset) −> Number

I know Andrew prefers the variants with ifAbsent, but I find them trickier to use for novices, especially because the ifAbsent variant generally almost always leads to a return in the middle of a statement
that is normally expected to return a number.  With the current set of methods I start out a method using indexOf and then having to use indexOf()startingAt()ifAbsent() inside a while loop a few statements later, which seems pretty inconsistent.

Can we have the missing variant listed above?

P.S.  We should do the same with lastIndexOf.

**Comment by apblack** [comment]
I just inserted indexOf()staringAt().  I continue to believe that this is A BAD IDEA, but I'm tired of arguing about it.

To summarize my argument: interfaces where the client has to check the result returned by a method before using it in the normal way are a known source of errors and should be avoided.  The canonical example is a file `open` procedure, which returns `NULL`, instead of failing, if the file can't be opened.  Correct usage of such an interface **requires** that the client check for `NULL` **every time** that they use `open`. 

indexOf ... is assumed to return an index.  It's in the very name of the method.  Therefor, it should return a valid index.  Without the `ifabsent` clause the client **must** check the result every time, before using it as an index.  This makes it very hard to use such a method in an expression.

If we had a stronger type system, or indexed strings with a type other than Number, as Michael has proposed, then the form without `ifabsent` would be a type error.

For teaching, I believe that it is a **bad idea** to show students interfaces like this.  They will assume that what we show them is good practice, and imitate it.  I don't want to demonstrate bad practice, and I don't want my students learning bad practice.

The solution to this problem is to move allow the libraries into the prelude, so that Kim can use the prelude that he wants, and I can use the prelude that i want.

**Comment by KimBruce** [comment]
I appreciate your willingness to make the addition.  While I agree with your general argument (esp. with files), I personally find the "ifAbsent" feature difficult to use in practice,  My preferred solution with file operations is to use match to distinguish a failed operation from a successful one.

Similarly, with indexOf I'd prefer to see 
    method indexOf(sub: String) -> PossibleNumber 

where 

def absent = object {
    method asString -> String {"absent"}
    method match(o: Object) -> MatchResult {   // is this necessary. it probably shouldn't be??
        if(o == self) then {
            SuccessfulMatch
        } else {
            FailedMatch
        }
    
    }
}

type PossibleNumber = absent | Number

The result could be processed as follows:
   match( source.indexOf(sub))
        case {(absent) -> ...}
        case {index: Number -> ...}

Unfortunately, the doesn't currently won't work in minigrace (not sure why!) as the case never matches
with absent.

At any rate, if I had my druthers, that's the way I would do it ...
(Can anyone fix my code so it does work?

**Comment by apblack** [comment]
I think that you mean to make a new SuccessfulMatch object, not return the class.

**Comment by KimBruce** [comment]
Yes, that works.  Thanks!

We do desperately need to update that part of the language spec.  Some of
the issues are that SuccessfulMatch takes two arguments (after ".new"),
while FailedMatch should take one (again after the ".new") -- and both
should start with a lower case letter.

Perhaps we already have something in the compiler (though I couldn't find
it), but it would be helpful to have a built in class singleton:

class singleton.new {
    method match(o: Object) -> MatchResult {
        if(o == self) then {
            SuccessfulMatch.new(self,list.empty)
        } else {
            FailedMatch.new(self)
        }
    }
}

Then a new singleton type could be defined by

def absent = object {
    inherits singleton.new
    method asString -> String {"absent"}
}

Notice that this is NOT what is stated in section 11.9 of the spec.  There
is implies there is no need to define a match method.

**Comment by apblack** [comment]
`Singleton.new` and `Singleton.named(s:String)` are in the standard prelude.  The difference between them is that `Singleton.named "helpful"` has an `asString` method that answers "helpful", rather than the default `asString`.
