### ISSUE TITLE
Dialects can't be found at command-line

### ISSUE THREAD

**Issue by reid47** [gracelang/minigrace#126]
I was trying to do some experiments using the `dialect.grace` dialect and `dialectExample.grace`. I navigated to `sample/dialects` and ran `make` to compile all of the dialects in there, which worked fine. Then I tried to use `dialect "dialectExample"` in another file (located at the highest level of the git directory, alongside `sample/`), and I got a seg fault. I then tried `dialect "sample/dialects/dialectExample` and got another seg fault. I then tried `import "dialectExample" as de`, and got a descriptive error:
```
Syntax error: Can't find dialectExample.grace or dialectExample.gcn; looked in [./].
  1: import "dialectExample" as de
-------------^^^^^^^^^^^^^^
```
When I tried `import "sample/dialects/dialectExample" as de`, I got this:
```
Syntax error: Can't find dialect.grace or dialect.gso; looked in [./].
  1: import "sample/dialects/dialectExample" as de
-------------^^^^^^^
```
Am I doing this wrong? Is there a proper way to use the dialects in `sample/dialects` that I'm missing?

**Comment by apblack** [comment]
Dialects are complicated.

On 22 Jul 2015, at 10:29, Reid Mitchell <notifications@github.com> wrote:

> I was trying to do some experiments using the dialect.grace dialect and dialectExample.grace. I navigated to sample/dialects and ran make to compile all of the dialects in there, which worked fine. Then I tried to use dialect "dialectExample" in another file (located at the highest level of the git directory, alongside sample/), and I got a seg fault. I then tried dialect "sample/dialects/dialectExample and got another seg fault. I then tried import "dialectExample" as de, and got a descriptive error:
> 
> Syntax error: Can't find dialectExample.grace or dialectExample.gcn; looked in [./].
>   1: import "dialectExample" as de
> -------------^^^^^^^^^^^^^^
> —
> 

Dialects need to be found TWICE — once at compile time, and once at runtime.  If you are running JS code, then that means that you need the .gct and .gso for loading the dialect at compile time, and the  .js for runtime.

In addition, whereas an import that references a source file will spawn a sub-process to compile it,  this doesn’t work with a dialect — this is a bug that could be fixed.

Changing the path in the import statement will help the compiler find the file at  compile time.  But that path is not available at runtime, and it’s not clear that it should be: the binary might we’ll be running on a different environment, and on a different computer, and in a different target language (such as in JS in a web browser.)

> When I tried import "sample/dialects/dialectExample" as de, I got this:
> 
> Syntax error: Can't find dialect.grace or dialect.gso; looked in [./].
>   1: import "sample/dialects/dialectExample" as de
> -------------^^^^^^^

So, rather than changing the dialect statement, make sure that the places where you want the compiler and the runtime to look re on your GRACE_MODULE_PATH variable.  The “looked in [./]” tells me you haven’t set up your environment correctly; the list in the brackets is the list of directories that was searched for the file in question, which i.e. printed [precisely to help diagnose problems like the one you are describing.
> Am I doing this wrong? Is there a proper way to use the dialects in sample/dialects that I'm missing?
> 

I don’t know if there is “right” way to use “samples”.  I believe that this directory was set up by Michael simply to store some sample dialects that he wrote for a paper.   I don’t believe that they were ever designed to be “used”.


I’ve spent quite a lot of time (too much, in hindsight) keeping these samples running, because the exercise parts of the compiler for which there are no tests.  But they are certainly not ready for “prime time”.

I’ve recently created a modules directory into which I’ve started putting modules and dialects that I want others to be able to use.  gUnit and minitest are there, and I’m slowly adding other utility modules, as I get time to write them.   The static compiled versions also go in modules, the dynamic compiled version into dynamic-modules, and the js compiled versions into js — this is to avoid one set of compilations overwriting the .gct files from another and updating the timestamps.    Then `make install` copies them all into the $(PREFIX)/lib/grace/modules directory in your installation — which directory should of course be on your GRACE_MODULE_PATH.

For development, just put modules, dynamic-modules and js on your GRACE_MODULE_PATH and everything should work.   If you use —verbose on your compiles, migrate will tell you where it is finding the modules.
