### ISSUE TITLE
Inconsistent naming in collections library

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#141]
The type Sequence<T> has method reversed which returns Sequence<T>.
The type List<T> (which extends Sequence<T>) has a method reverse that returns List<T>

I believe Grace will allow reverse to be overridden in List with a more specific return type.  Thus choose one spelling (either "reverse" or "reversed") and throw away the other.

**Comment by apblack** [comment]
I think that you are mis-reading the documentation.  Perhaps the difference in names is too subtle, and perhaps there are better ways of expressing what these methods do.  The difference between `reverse` and `reversed` is similar to the difference between `sort` and `sorted`: the first is a verb, expressing a mutation of the receiver, and the second is an adjective, describing the result. 

At the bottom of page 13 of the documentation for the basic libraries, it says (as part of the description of lists):

```
reverse −> List<T>
// mutates self in−place so that its elements are in the reverse order. Returns self. 
// Compare with reversed, which creates a new collection.
```

All `Sequences` (including `lists` and `ranges`) have a `reversed` method that answers a new objects of `SelfType`.  Unfortunately, because we don't yet have  `SelfType` in the type system, the signature for that method says that it returns `Sequence`.

Lists, which are mutable, _also_ have a method `reverse` that mutates the receiver, reversing the order of its elements.  See lines 765–781 of _collectionsPrelude_.

Can we add `reversed -> List<T>` to the methods that `List<T>` adds to `Sequence<T>`, or would this cause the `&` with `Sequence<T>` on line 72 of _collectionsPrelude_ to fail?   Since the change is co-variant, I think that it will be OK.  I just made the change in my working copy, and will commit it shortly.

**Comment by KimBruce** [comment]
In my particular uses (at least so far), the distinctions haven't mattered,
but I do find the distinctions in names very, very subtle, and hence
confusing.  (In the initial e-mail on this I didn't realize there was a
distinction.)  I don't have a suggestion for a better name, but wonder
whether we really need both.  I'd be happy just with the one that made a
new object.
