### ISSUE TITLE
Variable can be declared twice inside an object

### ISSUE THREAD

**Issue by Malachiain** [gracelang/minigrace#17]
Inside an object a def can be declared with the same name twice. Example:

    object {
      def a = 1
      def a = 2
    }

**Comment by ryan52** [comment]
I believe this may have been fixed.

The example given does produce the following error in JavaScript:
Syntax error: 'a' cannot be redeclared because it is already declared as a defdec on line 2 as well as here at line 3.
    in "17" (line 3, column 7)

The example given also produces the following error for C:
foobar.grace[3:7]: Syntax error: 'a' cannot be redeclared because it is already declared as a defdec on line 2 as well as here at line 3.
  2:   def a = 1
  3:   def a = 2
-----------^

**Comment by apblack** [comment]
Yes, this was fixed by the rewrite of the identifierresolution pass.
