### ISSUE TITLE
Programmer access to file I/O

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#231]
It would be highly desirable to extend minigrace to allow the programmer to read and write files.  it would be OK if these files had to first be loaded into the browser window.

**Comment by apblack** [comment]
Dmitri, I'm hoping that you can take a look a this. What's needed is some code in the io module (which lives in _js/gracelib.js_  that accesses the browser file system, but only when running in the browser.  Several of th eater methods there are already conditional on being in the browser.

**Comment by Dmitri-2** [comment]
Yes, I will try to have this done soon. I assume that the we want to have two methods on `gracecode_io` that allow files to be read and written within the browser. (I believe that code running within the browser is unable to access the local filesystem, due to security restrictions, so files would only be able to be written to/read from the IDE "local-storage" filesystem.) Does this sound okay?

**Comment by apblack** [comment]
It's a little more complicated than that.  There is already a method `open(path, mode)` that works when outside the browser; it returns a `FileStream` object, which has methods `write(str:String)`, `close` `getline`, etc.  You will need to add another case to `open(_,_)` that does something similar when inside the browser.  At present this works for _.gct_ files (that's used by the compiler), but not for other files.

You can model your code on what's done for reading and writing  _.gct_ files.  For reading a file, `open(_,_)` takes the gct string, splits it into lines, and saves the lines in an array in the file stream object.  Then `getline` simply returns the next line, and increments the `index`.  

The _io_ module is now documented, although perhaps not very thoroughly.  Start by writing some tests and making sure that they work at the command line.  Then make them run in the browser.   Because you are only modifying only _gracelib.js_, once you have the tests you should not actually need to compile any Grace files, so the code-and-test cycle should be fast.

**Comment by Dmitri-2** [comment]
I have a working update that allows files to be read and written through the io module in the web editor. 
Here are the methods that I have included for the `FileStream` object: 
```
write(str:String)
write
append(str:String)
getline
read
eof
pathname
close
==(1)
```

- Are there any other methods that I should include? (Such as a "seek" to skip lines when reading the file, or perhaps a method to read word-by-word?)
- Additionally, as I have designed this, when `getline` goes beyond the end of a file, it will throw a `GraceException`.  Is this behavior okay? 
- Also, if a file is "opened" that is not present in the web editor, it will be created. However, this newly created file will not appear in the list of files until after the web editor page is refreshed. Any changes to files already present in the IDE file list, will be updated and visible instantly. 

I have pushed a version of this to my fork of minigrace. See the file [here](https://github.com/Dmitri-2/minigrace/blob/master/js/gracelib.js#L2278).

**Comment by apblack** [comment]
Your question prompted me to take a look at stubs/io.grace, which is supposed to define the interface  `FileStream`.  It was out of date.  It _now_ says this:
```
type FileStream = Object & type {
    read -> String
        // returns the whole contents of the underlying file.
    getline -> String
        // returns the next line in the file, up to and including the next
        // newline.  If the end of the input is reached before a newline is
        // found, the result will not have a final newline.  If eof is true,
        // returns the empty string.
    write (s:String) -> Done
        // writes s to the file at the current position of the read-write pointer.
    close -> Done
        // closes the file.
    seek(n: Number) -> FileStream
        // moves the read position to n
    seekForward (n:Number) -> FileStream
        // moves the read/write position forward by n
    seekBackward (n:Number) -> FileStream
        // moved the read/write position backward by n
    iterator -> FileStream
        // returns self
    hasNext -> Boolean
        // returns true is next will return a character,
        // and false if it will raise an exception.
    next -> String
        // returns the next Unicode character from the file.
        // Raises IteratorExhausted if there is none
    readBinary(n:Number) -> Object
        // Returns an array containing the next n bytes
    writeBinary(bytes:Object) -> Number
        // appends bytes to the file.  Returns the number
        // of bytes written.
    pathname -> String
        // the name of the file underlying this fileStream
    eof -> Boolean
        // true if the read–write position is at the end of the file.
    isatty -> Boolean
        // true if this fileStream is interactive
    == (other) -> Boolean
        // true if self and other are the same FileStream object.  Note that
        // it is possible to have several distinct filestreams on the same
        // underlying file.
}
```
Note that the only one of these methods that raises an exception is `next`.  I'm nor sure that this is the best interface, that that's what we have right now.  The behaviour of `getline` is based on that of the Unix `getline` (3) function.

There is no need to add an `append` method; to append to a file, open it in **a**ppend mode.

> Also, if a file is "opened" that is not present in the web editor, it will be created. However, this newly created file will not appear in the list of files until after the web editor page is refreshed. Any changes to files already present in the IDE file list, will be updated and visible instantly.

I presume here that you mean "opened for **w**rite or **a**ppend".  It would certainly be better if it appeared in the file list immediately, but I think that we can live with this behaviour.   What if the program tries to read it after closing the write FileStream?  Will it be visible?

Ideally, you would write tests for all of these methods, and check that we get the same behaviour (i.e., the tests pass) on real files when running with `node`, and when running in the browser.

If it is too hard to implement some of these methods, like `readBinary(_)` and `writeBinary(_)` for example, you can just write a dummy method that raises a `notYetImplemented` exception.

**Comment by Dmitri-2** [comment]
### Q & A about the I/O Module:  
**Questions by @Dmitri-2 and Answers by @apblack**

> Should "seek" methods raise an exception if the input is not a number? (Or, should they default to setting the read/write position to the beginning of the file?)

It’s a TypeError for it not to be a number, and a RequestError for it not to be an integer.

>     Should "next" and "hasNext" use the same read/write pointer as "write(1)”?

Yes.

>     And, along these same lines, should "next" increment the read/write pointer by one when it returns a character?

Yes, so successive requests on next return the characters one by one, in order.

>    Should writes to a file (FileStream.write(1)) reset the "getline" counter to the beginning of the file? (So that it starts returning lines from the beginning of the file...)

Hmm...  I want this to be Unix compatible.   I think that there is only one read–write pointer, and that if you read some and then write, you will overwrite the next bytes that would have been written.  After writing, the read–write pointer is at the end of the section just written, so that additional writes will follow the prior writes.  So it would be weird to reset the read–write pointer to the start of the file after a write.

Readline doesn’t have its own pointer — it uses the same read–write pointer as read, write, and next.

>     What does it mean for a FileStream to be "interactive"? (Is it interactive when "writing" is allowed?)

It’s interactive if it is a “tty” in the Unix sense.  At present, it can’t be interactive in the web browser.

**Comment by Dmitri-2** [comment]
I committed a complete version of the io module that we have been discussing here to the `io-module` branch on `minigrace`. It is built to the specifications that we have talked about here. I hope to create a pull request as soon as I add the accompanying tests for the module, and any other modifications that need to be made.

**Comment by apblack** [comment]
This module long-ago became part of the master branch.  Any bugs that are found should be reported as new issues.
