### ISSUE TITLE
dialog box wording

### ISSUE THREAD

**Issue by kjx** [gracelang/minigrace#253]

**Comment by kjx** [comment]
This dialog box is backwards:

<img width="493" alt="dialog" src="https://user-images.githubusercontent.com/1917107/32318543-768d702a-c01c-11e7-9980-59e48dcef406.png">

it should be: Cancel to stop the loop, OK continue

that's what teaching HCI does to one.

**Comment by kjx** [comment]
or better still "Stop" to stop the look, or "Continue" to continue.

**Comment by apblack** [comment]
> On 2 Nov 2017, at 10:24 , kjx <notifications@github.com> wrote:
> 
> or better still "Stop" to stop the look, or "Continue" to continue.
> 

This can be done with a JQuery modal dialog.  If you have some one who knows how to use them, I would be happy to incorporate a fix.

Until then, I reversed the sense of the question — do you want to continue, rather than do you want to stop. And then it makes sense to switch the rôles of the buttons.

	Andrew

**Comment by apblack** [comment]
Here is the current message:

![screen shot 2018-01-09 at 14 19 15](https://user-images.githubusercontent.com/410893/34746262-3295449a-f548-11e7-9e78-da14163bb76a.png)

@kjx: do you have a student familiar with JavaScript who might be persuaded to make the change that you desire?

**Comment by kjx** [comment]
I think this is better; I don't have JS-capable students; I may get some once term restarts in March - J
