### ISSUE TITLE
odd block indentation

### ISSUE THREAD

**Issue by kjx** [gracelang/minigrace#318]
```
valueOf { print(1)
                              print(2)
                              print(3) }  
```

prints 

```
1
2
3
```

shouldn't it complain about a missing `print(_)print(_)print(_)` method?

**Comment by apblack** [comment]
I don't think so.

We have to decide if the increase in indentation on line 2 is to indicate a continuation line, or because a block has started.  Because line 1 has an unmatched `{`, line 2 starts a block, and the indentation is assumed to be that required by starting a block.

If instead you write
```
valueOf { print(1)
print(2)
print(3) }  
```
then you get `Syntax error: Please indent the body of a block`.

In hindsight, it may have been a mistake to use indentation for these two disparate purposes.  But the escaped newline convention used by Python (and shell) is so ugly ...

**Comment by kjx** [comment]
Yeah escaped newlines are surely evil.  
The indentation of `print(1)` starts at col 11.
But I don't see why when it comes to the indentation `print(2)`:
 - anything to the left of column 11 is an error 
 - at column 11, a new separate statement 
 - anything to the right of column 11 is a continuation.

**Comment by apblack** [comment]
> Given that indentation of print(1) starts at col 11,

Grace is not Haskell.  We count not the indentation of a statement; rather we count the indentation of the _line_ that contains the statement.  Hence, thou shalt say

    the indentation of the line containing `print(1)` is zero

It shalt also also be seen that the line containing `print(1)` openenth a block, as the `{` bears withness thereto

Hence, until the closing `}`
- every statement shall be indented 2 or more

It is not possible to both start a block on the current line, that is, to put a statement after an unmatched opening `{`, **and** to continue that statement on the next line.  If the statement won't all fit to the right of the `{`, start a new line after the `{`

**Comment by apblack** [comment]
> Grace is not Haskell

Which is why most of the Haskell-inspired work on indentation inference and specification was not much help to us.
