### ISSUE TITLE
Reserved words

### ISSUE THREAD

**Issue by KimBruce** [gracelang/minigrace#65]
If the user introduces an identifier (like outer) that happens to be a keyword of the language then the system essentially ignores the declaration and uses references as though it were the keyword.  Thus keywords really are reserved words, but there is no warning or error message when the programmer redeclares them.  There should be an error message emitted when the user does this rather than silently ignoring the declaration.

**Comment by apblack** [comment]
It would *really help* if you could provide programs that exemplify the bugs (perhaps in the js/tests/known-failing directory) so that I could focus on fixing the bugs rather than re-creating them.

Here is a program
```def b = object {
    def asString is public = "object b"
    def c is public = object {
        def asString is public = "object b.c"
//        def outer is public = 7
    }
}
print "Hello, world!"
print(b)
print(b.c)
print(b.c.outer)
```

As written, it correctly prints 
```
Hello, world!
object b
object b.c
object b
```
If I uncomment the def of outer, then the last print request prints 7 instead of "object b".

This seems to be correct behavior to me, based on minigrace's (outdated) interpretation of outer as a method.  Perhaps now that outer is like **super**, we should make it a keyword and not allow it to be re-defined at all?

**Comment by KimBruce** [comment]
Sorry, here is code that gives the same message on my web installation and on yours:
```
def a = object {
  def x = 7
  def z = object {
    var outer := 3
    print(outer)
  }
}
```
---------------
NoSuchMethod at line 5 of test: Requested confidential method 'outer' on object an object from outside.
  called from execution environment

**Comment by apblack** [comment]
As of commit 4eff0a2 this program now produces the message:
```
Syntax error: outer is a reserved name and cannot be re-declared.
  3:   def z = object {
  4:     var outer := 3
-------------^^^^^
```
