### ISSUE TITLE
self can be assigned

### ISSUE THREAD

**Issue by apblack** [gracelang/minigrace#93]
Some student programs managed to assign to **self**.
The compiled code won't compile (in the C case) or run (in the JS case).

self should be recognized as a keyword.  The same should be true for **outer** (issue #65) and **super**

**Comment by KimBruce** [comment]
I would have called it a reserved word rather than a keyword, but I agree with the idea.

From everyone’s favorite source of wisdom, stackoverflow:     :-)

Keywords have a special meaning in a language, and are part of the syntax.

Reserved words are words that cannot be used as identifiers (variables, functions, etc.), because they are reserved by the language.

In practice most keywords are reserved words and vice versa. But because they're two different things it may happen that a keyword is not a reserved word (e.g. a keyword only has meaning in a special context, and can therefore be used as an identifier), or a reserved word is not a keyword (e.g. because it is reserved for future use).

Update: Some examples as given by others that illustrate the distinction:

In Java, goto is a reserved word but not a keyword (as a consequence, you cannot use it at all)
Fortran has no reserved words, all keywords (if, then, etc.) can be used as identifiers

Kim

**Comment by apblack** [comment]
This is fixed in 4eff0a2.  I introduced the concept of a reserved name and put true, false, self, super and outer on the list.  I'm not sure this is inexactly what the final language design should do, but I don't want novices assigning to those names, or trying to re-declare them.
